### ISSUE TITLE
Is write_to_bytes incorrectly defined?

### ISSUE THREAD

**Issue by collinlee** [Shikugawa/proxy-wasm-rust-sdk-grpc-example#1]
In the rust code for lib.rs I get

 let message = req.write_to_bytes().unwrap();
    |                           ^^^^^^^^^^^^^^ method not found in `HelloRequest`

How is write_to_bytes defined in HelloRequest?

**Comment by collinlee** [comment]
nevermind I needed

use protobuf::Message;

**Comment by Pawan-Bishnoi** [comment]
Loved this project.
You might want to ⭐ this project too 😃
